apiVersion: v1
kind: ConfigMap
metadata:
  namespace: redis-cluster
  name: redis
  labels:
    app: redis
data:
  redis-server.sh: |
    #!/bin/sh
    # Fix my own IP.
    # https://rancher.com/blog/2019/deploying-redis-cluster/
    REDIS_NODES=/var/lib/redis/nodes.conf
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    cluster-enabled yes
    cluster-config-file /var/lib/redis/nodes.conf
    cluster-node-timeout 5000
    dir /var/lib/redis
    port 6379
