---
os: linux
dist: trusty
sudo: required
# https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2
# for the new trusty image.
group: edge

env:
  global:
    - GOROOT=$HOME/git/go
    - GOPATH=$HOME
  matrix:
    # This is the chrooted archlinux environemnt to check host.yml.
    # https://github.com/mikkeloscar/arch-travis/blob/master/README.md
    - CI_TEST_HOST_ENV=1 ARCH_TRAVIS_ARCH=x86_64 ARCH_TRAVIS_CLEAN_CHROOT=1 ARCH_TRAVIS_CONFIRM_YES=1
    # This is the ubuntu environment, to check guest.yml.
    - CI_TEST_GUEST_ENV=1
    # This is the k8s cluster environment, to check cluster.yml.
    - CI_TEST_CLUSTER_ENV=1
    # This is the k8s master environment, to check master.yml.
    - CI_TEST_MASTER_ENV=1
    # This is the k8s node environment, to check node.yml.
    - CI_TEST_NODE_ENV=1

language: c

compiler:
  - gcc

arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    # pacman packages
    - openssh
    - git
    - python
    - python-setuptools
    - python-pip
    #- procps-ng
    #- reflector
    # aur
    #- screenfetch-git
  script:
    # script run under chrooted environment
    #- "sudo screenfetch"
    #- "reflector --verbose -l 20 --sort rate -p https"
    - "sudo -E make ci-test-host"

script:
  - if [[ "${CI_TEST_HOST_ENV}" == "1" ]]; then curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash; fi
  - if [[ "${CI_TEST_GUEST_ENV}" == "1" ]]; then sudo -E make ci-test-guest; fi
  - if [[ "${CI_TEST_CLUSTER_ENV}" == "1" ]]; then sudo -E make ci-test-cluster; fi
  - if [[ "${CI_TEST_MASTER_ENV}" == "1" ]]; then sudo -E make ci-test-master; fi
  - if [[ "${CI_TEST_NODE_ENV}" == "1" ]]; then sudo -E make ci-test-node; fi
