---
- name: bootstrap k8s cluster
  hosts: cluster
  gather_facts: true
  vars:
    guest_management_network: 192.168.122
  tasks:
    - name: update hostname to be sync with the inventory host name
      hostname: name={{ inventory_hostname_short }}
      become: true

    - name: setup console access
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0,38400n8"'
        owner: root
        group: root
        mode: 0644
      register: console
      become: true

    - name: update /boot/grub/grub.cfg to reflect the console change
      command: grub-mkconfig -o /boot/grub/grub.cfg
      become: true
      when: console.changed

    - name: update files under /etc
      template:
        src: "templates/etc/{{ item }}.j2"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - network/interfaces
      become: true

    - name: assign ens5 IP address
      template:
        src: templates/etc/network/interfaces.d/ens5.j2
        dest: /etc/network/interfaces.d/ens5
        mode: 0644
        owner: root
        group: root
      register: ens5

    - name: bring up ens5 interface
      command: ifup -a
      become: true
      changed_when: false
      when: ens5.changed

    - name: install docker for ubuntu16.04 or above
      apt: name={{ item }} state=present update_cache=false
      with_items:
        - docker.io
      become: true
      when: ansible_distribution_version == "16.04"

    - name: add user to the docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: docker
      become: true
