---
- name: bootstrap k8s cluster
  hosts: cluster
  gather_facts: true
  tasks:
    - name: setup console access
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0,38400n8"'
        owner: root
        group: root
        mode: 0644
      register: console
      become: true

    - name: update /boot/grub/grub.cfg to reflect the console change
      command: grub-mkconfig -o /boot/grub/grub.cfg
      become: true
      when: console.changed

    - name: update /etc/hosts for air.local reachability
      copy:
        src: files/etc/hosts
        dest: /etc/hosts
        mode: 0644
        owner: root
        group: root
      become: true

    - name: update /etc/network/interfaces
      copy:
        src: files/etc/network/interfaces
        dest: /etc/network/interfaces
        mode: 0644
        owner: root
        group: root
      become: true

    - name: assign bond0 IP address
      template:
        src: templates/etc/network/interfaces.d/bond0.j2
        dest: /etc/network/interfaces.d/bond0
        mode: 0644
        owner: root
        group: root
      become: true
      register: bond0

    - name: bring up bond0 interface
      command: ifup -a
      become: true
      changed_when: false
      when: bond0.changed

    - name: install docker for ubuntu16.04 or above
      apt: name={{ item }} state=present update_cache=false
      with_items:
        - docker.io
      become: true
      when: ansible_distribution_version == "16.04"

    - name: add user to the docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: docker
      become: true

    - name: allow the insecure air.local local docker registry access
      lineinfile:
        path: /etc/systemd/system/multi-user.target.wants/docker.service
        regexp: "^ExecStart"
        line: "ExecStart=/usr/bin/dockerd --insecure-registry air.local:5000 -H fd:// $DOCKER_OPTS"
      become: true
      when: ansible_distribution_version == "16.04"

    - name: restart docker daemon to reflect the previous change
      systemd:
        name: docker
        state: restarted
        daemon_reload: true
      become: true
      when: ansible_distribution_version == "16.04"

    - name: install gce encription key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      become: true

    - name: add gce kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list
      become: true

    - name: install kubernetes packages
      apt: name={{ item }} state=latest update_cache=false
      with_items:
        - kubelet
        - kubeadm
        - kubernetes-cni
      become: true
      when: ansible_distribution_version == "16.04"

- name: bootstrap kubernetes master
  import_playbook: master.yml

- name: bootstrap kubernetes node
  import_playbook: node.yml

- name: bootstrap kubernetes network
  import_playbook: network.yml
  when: not travis_ci|bool
