---
- name: host provisioning playbook
  hosts: host
  vars:
    ci: false
    latest: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
    cluster_node_emulator: /usr/bin/qemu-system-x86_64
    cluster_node_arch: x86_64
    cluster_node_machine: pc-i440fx-2.11
    cluster_node_disk_type: block
    cluster_node_disk_path: /dev/images
    cluster_node_disk_source_type: dev
    cluster_node_intf0_dev_prefix: ens3-
    cluster_node_network: 172.31.255
    cluster_nodes:
      - { id: '10', type: head }
      - { id: '11', type: work }
      - { id: '12', type: work }
      - { id: '13', type: work }
      - { id: '14', type: work }
      - { id: '15', type: work }
      - { id: '20', type: head }
      - { id: '21', type: work }
      - { id: '22', type: work }
      - { id: '23', type: work }
      - { id: '24', type: work }
      - { id: '25', type: work }
      - { id: '30', type: head }
      - { id: '31', type: work }
      - { id: '32', type: work }
      - { id: '33', type: work }
      - { id: '34', type: work }
      - { id: '35', type: work }
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOROOT') }}/bin:{{ lookup('env', 'GOPATH') }}/bin:/usr/bin:/bin"
  gather_facts: false
  tasks:
    - name: update files under /etc
      template:
        src: "templates/etc/{{ item }}.j2"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - hosts
        - modprobe.d/modprobe.conf
      become: true
      when: not ci|bool

    - name: install package(s)
      pacman:
        state: present
        update_cache: true
        name:
          - go
          - git
          - docker
      become: true
      when: latest|bool

    - name: undefine libvirt guest network
      virt_net: name=default state=absent
      become: true
      when: not ci|bool

    - name: define libvirt guest network
      virt_net:
        name: default
        state: present
        xml: "{{ lookup('template', 'templates/etc/libvirt/qemu/networks/default.xml.j2') }}"
      become: true
      when: not ci|bool

    - name: undefine libvirt guest
      virt:
        name: "{{ item.type }}{{ item.id }}"
        command: undefine
      with_items: "{{ cluster_nodes }}"
      become: true
      ignore_errors: true
      when: not ci|bool

    - name: define libvirt guest
      virt:
        command: define
        xml: "{{ lookup('template', 'templates/etc/libvirt/qemu/{{ item.type }}.xml.j2') }}"
      with_items: "{{ cluster_nodes }}"
      become: true
      when: not ci|bool

    # we will use systemd cgroup for the container runtime.
    # https://kubernetes.io/docs/setup/cri/
    - name: allow the insecure host.local local docker registry access
      lineinfile:
        path: /etc/systemd/system/multi-user.target.wants/docker.service
        regexp: "^ExecStart"
        line: "ExecStart=/usr/bin/dockerd --insecure-registry host.local:5000 -H fd:// $DOCKER_OPTS"
      become: true
      when: not ci|bool

    - name: restart docker service to reflect the registry change
      systemd: name=docker enabled=true state=restarted
      become: true
      when: not ci|bool

    - name: run the local docker registry
      docker_container:
        name: registry
        image: registry:2
        state: started
        restart: yes
        restart_policy: always
        ports:
          - "5000:5000"
      when: not ci|bool

    - name: install the prometheus
      import_tasks: tasks/prometheus.yaml
      when: latest|bool
