---
- name: host provisioning playbook
  hosts: host
  vars:
    ci: false
    latest: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
    guest_emulator: /usr/bin/qemu-system-x86_64
    guest_arch: x86_64
    guest_machine: pc-i440fx-2.11
    guest_disk_type: block
    guest_disk_path: /dev/images
    guest_disk_source_type: dev
    guest_intf0_dev_prefix: ens3-
    guest_intf1_dev_prefix: ens4-
    guest_intf2_dev_prefix: ens5-
    guest_management_network: 192.168.122
    guests:
      - { id: '1',  type: vm }
      - { id: '2',  type: vm }
      - { id: '10', type: kube }
      - { id: '11', type: kube }
      - { id: '12', type: cam  }
      - { id: '13', type: cam  }
      - { id: '20', type: node }
      - { id: '21', type: node }
      - { id: '30', type: node }
      - { id: '31', type: node }
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOROOT') }}/bin:{{ lookup('env', 'GOPATH') }}/bin:/usr/bin:/bin"
  gather_facts: false
  tasks:
    - name: update files under /etc
      template:
        src: "templates/etc/{{ item }}.j2"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - hosts
        - modprobe.d/modprobe.conf
        - systemd/network/br0.network
      become: true
      when: not ci|bool

    - name: install package(s)
      pacman:
        state: present
        update_cache: true
        name:
          - kubectl
      become: true

    - name: undefine libvirt guest network
      virt_net: name=default state=absent
      become: true
      when: not ci|bool

    - name: define libvirt guest network
      virt_net:
        name: default
        state: present
        xml: "{{ lookup('template', 'templates/etc/libvirt/qemu/networks/default.xml.j2') }}"
      become: true
      when: not ci|bool

    - name: undefine libvirt guest
      virt:
        name: "{{ item.type }}{{ item.id }}"
        command: undefine
      with_items: "{{ guests }}"
      become: true
      ignore_errors: true
      when: not ci|bool

    - name: define libvirt guest
      virt:
        command: define
        xml: "{{ lookup('template', 'templates/etc/libvirt/qemu/{{ item.type }}.xml.j2') }}"
      with_items: "{{ guests }}"
      become: true
      when: not ci|bool

    - name: run the local docker registry
      docker_container:
        name: registry
        image: registry:2
        state: started
        restart: yes
        restart_policy: always
        ports:
          - "5000:5000"
      when: not ci|bool

    - name: install the latest golang
      import_tasks: tasks/golang.yml
      when: latest|bool

    - name: install the prometheus
      import_tasks: tasks/prometheus.yml
      when: latest|bool
