---
- name: setup arch based kube master
  hosts: master
  vars:
    gobootstrap: /usr/lib/go
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    cluster_podcidr: 10.244.0.0/16
    ldflags: >
      -X k8s.io/kubernetes/pkg/version.gitVersion=v1.14.2
      -X k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitVersion=v1.14.2
      -X k8s.io/kubernetes/pkg/kubectl/version.gitVersion=v1.14.2
    latest: false
  gather_facts: true
  tasks:
    - name: install package(s)
      pacman:
        state: present
        update_cache: true
        name:
          - go
          - gcc
          - make
      become: true
      when: latest|bool

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700
      when: latest|bool

    - name: install the latest golang
      import_tasks: tasks/golang.yml
      when: latest|bool

    - name: install etcd
      import_tasks: tasks/etcd.yml
      when: latest|bool

    - name: get the kubernetes
      git:
        repo: "{{ gitsite }}kubernetes/kubernetes"
        dest: "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes"
        update: yes
        ssh_opts: "-o StrictHostKeyChecking=no"
      register: k8s
      environment:
        GOPATH: "{{ lookup('env', 'GOPATH') }}"
      when: latest|bool

    - name: build openapi-gen and go2make for openapi.go generation
      command: go install -ldflags "{{ ldflags }}" "{{ item }}"
      args:
        chdir: "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes"
      with_items:
        - ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
        - ./hack/make-rules/helpers/go2make
      environment:
        GOROOT: "{{ lookup('env', 'GOROOT') }}"
        GOPATH: "{{ lookup('env', 'GOPATH') }}"
        PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"
      when: k8s.before != k8s.after and latest|bool

    - name: generate openapi.go
      make:
        chdir:  "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes"
        target: ./pkg/generated/openapi/openapi.go
        file:   ./Makefile.generated_files
        params:
          CALLED_FROM_MAIN_MAKEFILE: 1
          KUBE_VERBOSE: 2
          PRJ_SRC_PATH: .
          META_DIR:     .make
          OUT_DIR:      _output
          BIN_DIR:       "{{ lookup('env', 'GOPATH') }}/bin"
      when: k8s.before != k8s.after and latest|bool

    - name: copy generated openapi.go
      copy:
        remote_src: true
        src:  "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes/_output/local/go/src/{{ item }}"
        dest: "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes/{{ item }}"
        mode: 0755
      with_items:
        - pkg/generated/openapi/openapi.go
      when: k8s.before != k8s.after and latest|bool

    # https://kubernetes.io/docs/concepts/overview/components/
    - name: build k8s components
      command: go install -ldflags "{{ ldflags }}" "{{ item }}"
      args:
        chdir: "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes"
      with_items:
        - ./cmd/kubeadm
        - ./cmd/kubectl
        - ./cmd/kubelet
        - ./cmd/kube-proxy
        - ./cmd/kube-apiserver
        - ./cmd/kube-scheduler
        - ./cmd/kube-controller-manager
      environment:
        GOROOT: "{{ lookup('env', 'GOROOT') }}"
        GOPATH: "{{ lookup('env', 'GOPATH') }}"
        PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"
      when: k8s.before != k8s.after and latest|bool

    - name: download the kubeadm and kubelet for nodes
      fetch:
        src: "{{ lookup('env', 'GOPATH') }}/bin/{{ item }}"
        dest: "/tmp/{{ ansible_user_id }}/{{ item }}"
        flat: yes
      with_items:
        - kubeadm
        - kubelet

    - name: check if the master is already initialized
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet
      changed_when: false

    - name: initialize the cluster master!
      command: |
        kubeadm init --pod-network-cidr "{{ cluster_podcidr }}"
          --apiserver-advertise-address "{{ cluster_node_ip }}"
      become: true
      environment:
        GOROOT: "{{ lookup('env', 'GOROOT') }}"
        GOPATH: "{{ lookup('env', 'GOPATH') }}"
        PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"
      register: kubeadm
      when: kubelet.stat.exists == false

    - name: get API token, API server, and certificate hash
      set_fact:
        cluster_apiserver: "{{kubeadm.stdout|regex_search(regexp, '\\1')|list|first}}"
        cluster_token: "{{kubeadm.stdout|regex_search(regexp, '\\2')|list|first}}"
        cluster_cert_hash: "{{kubeadm.stdout|regex_search(regexp, '\\3')|list|first}}"
      vars:
        regexp: 'kubeadm join (\S+) --token (\S+) --discovery-token-ca-cert-hash (\S+)'
      when: kubeadm.changed == true
      changed_when: false

    - name: fetch the admin.conf for kubectl to work
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ lookup('env', 'HOME') }}/.kube/config"
        flat: true
      become: yes
      when: kubeadm.changed == true
      changed_when: false
