---
- name: setup arch based kube master
  hosts: master
  vars:
    gobootstrap: /usr/lib/go
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    cluster_podcidr: 10.244.0.0/16
  gather_facts: true
  tasks:
    - name: install package(s)
      pacman:
        state: present
        update_cache: true
        name:
          - go
          - gcc
          - make
      become: true

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: install the latest golang
      import_tasks: tasks/golang.yml

    - name: install etcd
      import_tasks: tasks/etcd.yml

    - name: get the kubernetes
      git:
        repo: "{{ gitsite }}kubernetes/kubernetes"
        dest: "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes"
        update: yes
        ssh_opts: "-o StrictHostKeyChecking=no"
      register: git
      environment:
        GOPATH: "{{ lookup('env', 'GOPATH') }}"

    - name: install kubeadm, kubelet, kube-apiserver
      command: go install "./cmd/{{ item }}"
      args:
        chdir: "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes"
      with_items:
        - kubeadm
        - kubelet
        - kube-apiserver
        - kube-controller-manager
      when: git.before != git.after
      environment:
        GOROOT: "{{ lookup('env', 'GOROOT') }}"
        GOPATH: "{{ lookup('env', 'GOPATH') }}"
        PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"

    - name: check if the master is already initialized
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet
      changed_when: false

    - name: initialize the cluster master!
      command: |
        kubeadm init --pod-network-cidr "{{ cluster_podcidr }}"
          --apiserver-advertise-address "{{ cluster_node_ip }}"
      become: true
      register: kubeadm
      when: kubelet.stat.exists == false and ansible_distribution_version == "18.04"

    - name: get API token, API server, and certificate hash
      set_fact:
        cluster_apiserver: "{{kubeadm.stdout|regex_search(regexp, '\\1')|list|first}}"
        cluster_token: "{{kubeadm.stdout|regex_search(regexp, '\\2')|list|first}}"
        cluster_cert_hash: "{{kubeadm.stdout|regex_search(regexp, '\\3')|list|first}}"
      vars:
        regexp: 'kubeadm join (\S+) --token (\S+) --discovery-token-ca-cert-hash (\S+)'
      when: kubeadm.changed == true
      changed_when: false

    - name: fetch the admin.conf for kubectl to work
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ lookup('env', 'HOME') }}/.kube/config"
        flat: true
      become: yes
      when: kubeadm.changed == true
      changed_when: false
