---
- name: setup ubuntu based kube master
  hosts: master
  vars:
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go-1.6
    latest: true
    cluster_podcidr: 10.244.0.0/16
  gather_facts: true
  tasks:
    - name: install apt packages
      apt: name={{ item }} state=present update_cache=true
      with_items:
        - golang-1.6
      become: true

    - name: disable swap on the master for kubelet1.8 or above to run
      command: swapoff -a
      become: true
      changed_when: false

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: install the latest golang
      import_tasks: tasks/golang.yml
      when: latest|bool

    - name: get the latest etcd
      command: go get -u {{ item }}
      with_items:
        - github.com/coreos/etcd/cmd/etcd
        - github.com/coreos/etcd/cmd/etcdctl
      environment:
        GOROOT: "{{ lookup('env', 'GOROOT') }}"
        GOPATH: "{{ lookup('env', 'GOPATH') }}"
        PATH: "{{ lookup('env', 'GOROOT') }}/bin:{{ lookup('env', 'GOPATH') }}/bin:/usr/bin:/bin"
      when: latest|bool

    - name: install encription key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      become: true

    - name: add gce kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list
      become: true

    - name: install kubernetes packages
      apt: name={{ item }} state=latest update_cache=false
      with_items:
        - kubelet
        - kubeadm
        - kubernetes-cni
      become: true
      when: ansible_distribution_version == "16.04"

    - name: check if the master is already initialized
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet
      changed_when: false

    - name: initialize the cluster master!
      command: |
        kubeadm init --pod-network-cidr "{{ cluster_podcidr }}"
          --apiserver-advertise-address "{{ cluster_node_ip }}"
      become: true
      register: kubeadm
      when: kubelet.stat.exists == false and ansible_distribution_version == "16.04"

    - name: get API token, API server, and certificate hash
      set_fact:
        cluster_token: "{{kubeadm.stdout|regex_search(regexp, '\\1')|list|first}}"
        cluster_apiserver: "{{kubeadm.stdout|regex_search(regexp, '\\2')|list|first}}"
        cluster_cert_hash: "{{kubeadm.stdout|regex_search(regexp, '\\4')|list|first}}"
      vars:
        regexp: 'kubeadm join --token (\S+) (\S+) (\S+) (\S+)'
      when: kubeadm.changed == true
      changed_when: false

    - name: fetch the admin.conf for kubectl to work
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ lookup('env', 'HOME') }}/.kube/config"
        flat: true
      become: yes
      when: kubeadm.changed == true
      changed_when: false
