---
- name: provision the cluster networking
  hosts: localhost
  connection: local
  vars:
    networking: weave
    manifest:
      flannel: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      calico:  https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml
      weave: https://git.io/weave-kube-1.6
    travis_ci: false
  gather_facts: false
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOROOT') }}/bin:{{ lookup('env', 'GOPATH') }}/bin:/usr/bin:/bin"
  tasks:
    - name: get the kubectl
      command: go get -u {{ item }}
      with_items:
        - k8s.io/kubernetes/cmd/kubectl

    - name: delete the old networking module
      command: "kubectl delete --force=true -f {{ item.manifest }}"
      when: item.name != networking
      failed_when: false
      with_items:
        - { name: flannel, manifest: "{{ manifest.flannel }}" }
        - { name: calico,  manifest: "{{ manifest.calico }}" }
        - { name: weave,   manifest: "{{ manifest.weave }}" }
      changed_when: false

    - name: apply the new networking module
      command: "kubectl apply --force=true -f {{ item.manifest }}"
      when: item.name == networking
      with_items:
        - { name: flannel, manifest: "{{ manifest.flannel }}" }
        - { name: calico,  manifest: "{{ manifest.calico }}" }
        - { name: weave,   manifest: "{{ manifest.weave }}" }
      changed_when: false
