---
- name: setup ubuntu based kube node
  hosts: node
  gather_facts: true
  vars:
    cluster_token: "{{ hostvars[master]['cluster_token'] }}"
    cluster_apiserver: "{{ hostvars[master]['cluster_apiserver'] }}"
    cluster_cert_hash: "{{ hostvars[master]['cluster_cert_hash'] }}"
    travis_ci: false
  tasks:
    - name: check if I'm already in the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet
      become: true
      changed_when: false

    - name: join the cluster!
      command: |
        kubeadm join --token "{{ cluster_token }}" "{{ cluster_apiserver }}"
          --discovery-token-ca-cert-hash "{{ cluster_cert_hash }}"
      become: true
      when: kubelet.stat.exists == false and ansible_distribution_version == "18.04"
