---
- name: setup arch based kube node
  hosts: node
  gather_facts: true
  vars:
    ci: false
    cluster_token: "{{ hostvars[master]['cluster_token'] }}"
    cluster_apiserver: "{{ hostvars[master]['cluster_apiserver'] }}"
    cluster_cert_hash: "{{ hostvars[master]['cluster_cert_hash'] }}"
  tasks:
    - name: upload the kubeadm and kubelet to nodes
      copy:
        src:  "/tmp/{{ ansible_user_id }}/{{ item }}"
        dest: "{{ lookup('env', 'GOPATH') }}/bin/{{ item }}"
        mode: 0755
      with_items:
        - kubeadm
        - kubelet

    - name: check if I'm already in the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet
      become: true
      changed_when: false

    - name: join the cluster!
      command: |
        kubeadm join --token "{{ cluster_token }}" "{{ cluster_apiserver }}"
          --discovery-token-ca-cert-hash "{{ cluster_cert_hash }}"
      become: true
      environment:
        PATH: "{{ lookup('env', 'GOPATH') }}/bin:/usr/bin:/bin"
      when: not ci|bool and not kubelet.stat.exists|bool
