---
- name: teardown kubernetes cluster
  hosts: cluster
  gather_facts: false
  tasks:
    - name: reset the kubernetes configuration with kubeadm
      command: kubeadm reset -f
      environment:
        PATH: "{{ lookup('env', 'GOPATH') }}/bin:/usr/bin:/bin"
      become: true
