---
- name: setup ubuntu guest
  hosts: ubuntu
  vars:
    latest: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    srcpath: "{{ lookup('env', 'HOME') }}/src/"
    gobootstrap: /usr/lib/go-1.6
    guest_management_network: 172.31.255
  gather_facts: true
  tasks:
    - name: install console apps
      apt:
        state: present
        update_cache: true
        name:
          - vim
          - tmux
          - mutt
          - cscope
          - tree
          - jq
          - aspell
          - aspell-en
      become: true

    - name: install network tools
      apt:
        state: present
        update_cache: false
        name:
          - curl
          - elinks
          - tcpdump
      become: true

    - name: install developer tools
      apt:
        state: present
        update_cache: false
        name:
          - binutils
          - bc
          - g++
          - git
          - gdb
          - make
          - autoconf
          - automake
          - libtool
          - bzip2
          - unzip
          - golang-1.6
          - python-all
          - python-pip
          - python-lxml
          - libssl-dev
          - libffi-dev
      become: true

    # https://ownyourbits.com/2018/06/13/transparently-running-binaries-from-any-architecture-in-linux-with-qemu-and-binfmt_misc/
    - name: install Qemu based cross environment
      apt:
        state: present
        update_cache: false
        name:
          - qemu
          - qemu-user-static
          - qemu-user
          - binfmt-support
      become: true

    # https://docs.nvidia.com/sdk-manager/download-run-sdkm/index.html
    - name: install graphics libraries for JetPack Nvidia developer kit
      apt:
        state: present
        update_cache: false
        name:
          - libgconf-2-4
          - libcanberra-gtk-module
          - libgtk-3-0
          - libxss1
          - libnss3-dev
      become: true

    - name: update hostname to be sync with the inventory host name
      hostname: name={{ inventory_hostname_short }}
      become: true

    - name: make console access through ttyS0
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0,38400n8"'
        owner: root
        group: root
        mode: 0644
      register: console
      become: true

    - name: update the /boot/grub/grub.cfg to reflect the change
      command: grub-mkconfig -o /boot/grub/grub.cfg
      become: true
      when: console.changed

    - name: make sure /etc/network/interfaces.d exists
      file: path=/etc/network/interfaces.d state=directory
      become: true

    - name: update files under /etc
      template:
        src: "templates/etc/{{ item }}.j2"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - hosts
      become: true

    - name: create git root directory
      file: path={{ item }} state=directory mode=0700
      with_items:
        - "{{ gitpath }}"
        - "{{ srcpath }}"

    - name: install docker package
      import_tasks: tasks/docker.yml

    - name: install docker-compose package
      import_tasks: tasks/docker-compose.yml

    - name: install the latest golang
      import_tasks: tasks/golang.yml

    - name: install the usuful go packages
      import_tasks: tasks/gopkg.yml

    - name: install the latest nodejs
      import_tasks: tasks/nodejs.yml

    - name: install the latest gcloud
      import_tasks: tasks/gcloud.yml

    - name: add user to the docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: docker
      become: true

    - name: install the latest golang
      import_tasks: tasks/golang.yml

    - name: install the google cloud SDK
      import_tasks: tasks/gcloud.yml
