apiVersion: v1
kind: PersistentVolume
metadata:
  name: tikv11
  labels:
    app: tikv-cluster
    node: work11
    volume: tikv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /var/lib/tikv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - work11
