apiVersion: v1
kind: PersistentVolume
metadata:
  name: tikv13
  labels:
    app: tikv-cluster
    node: work13
    volume: tikv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disk/tikv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - work13
