apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    volume: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.255.254
    path: "/srv/nfs/k8s/mysql"
    readOnly: false
