---
- name: install the latest perl packages
  import_tasks: tasks/perl.yml

- name: install the latest python packages
  import_tasks: tasks/python.yml

- name: install the latest Open vSwitch
  import_tasks: tasks/openvswitch.yml

- name: install the latest golang
  import_tasks: tasks/golang.yml

- name: install the OpenTracing
  import_tasks: tasks/tracing.yml

- name: install the latest terraform
  import_tasks: tasks/terraform.yml
  when: not travis_ci|bool

- name: configure the docker-compose environment
  import_tasks: tasks/docker-compose.yml
  when: latest|bool and not travis_ci|bool

- name: install the latest protobuf
  import_tasks: tasks/protobuf.yml
  when: latest|bool and not travis_ci|bool
