---
# https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository
- name: remove the default docker packages, if there is
  apt:
    name: [docker, docker-engine, docker-io]
    state: absent
  become: true

- name: allow the repository access over HTTPS
  apt:
    name: [apt-transport-https, ca-certificates, curl, software-properties-common]
    state: present
  become: true

- name: setup docker PGP key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
  become: true

- name: install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: true
  become: true
