---
- name: clone the golang git repo
  git:
    repo: "{{ gitsite }}golang/go"
    dest: "{{ gitpath }}go"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git

- name: build & install the latest golang
  shell: GOROOT_BOOTSTRAP={{ gobootstrap }} ./make.bash
  args:
    chdir: "{{ gitpath }}/go/src"
  when: git.before != git.after
