---
- name: get some useful golang packages and tools
  command: go get -u {{ item }}
  with_items:
    - golang.org/x/tools/cmd/godoc
    - golang.org/x/tools/cmd/present
    - golang.org/x/tools/cmd/goimports
    - github.com/golang/dep/cmd/dep
    - github.com/golang/mock/gomock
    - github.com/golang/mock/mockgen
    - github.com/kardianos/govendor
    - github.com/UnnoTed/fileb0x
    - github.com/streadway/amqp
    - github.com/derekparker/delve/cmd/dlv
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"

- name: get some gRPC related golang packages and tools
  command: go get -u {{ item }}
  with_items:
    - google.golang.org/grpc
    - github.com/golang/protobuf/protoc-gen-go
    - github.com/gogo/protobuf/protoc-gen-gofast
    - github.com/mwitkow/go-proto-validators/protoc-gen-govalidators
    - github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"

- name: get opentracing related golang packages and tools
  command: go get -u {{ item }}
  with_items:
    - github.com/opentracing/opentracing-go
    - github.com/opentracing-contrib/go-stdlib/nethttp
    - github.com/opentracing-contrib/go-amqp/amqptracer
    - github.com/openzipkin/zipkin-go-opentracing
    - github.com/bg451/opentracing-example
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"
