---
- name: get the kubectl
  git:
    repo: "{{ gitsite }}kubernetes/kubernetes"
    dest: "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
  register: git
  environment:
    GOPATH: "{{ lookup('env', 'GOPATH') }}"

- name: install the kubectl
  command: go install ./cmd/kubectl
  args:
    chdir: "{{ lookup('env', 'GOPATH') }}/src/k8s.io/kubernetes"
  when: git.before != git.after
  environment:
    GOROOT: "{{ lookup('env', 'GOROOT') }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
    PATH: "{{ lookup('env', 'GOPATH') }}/bin:{{ lookup('env', 'GOROOT') }}/bin:/usr/bin:/bin"
