apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: redis-cluster
  name: redis-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      name: redis-2
  template:
    metadata:
      labels:
        app: redis
        name: redis-2
    spec:
      containers:
        - name: redis
          image: redis:6.0.10-alpine
          command: ["/etc/redis/redis-server.sh"]
          args: [redis-server, "/etc/redis/redis.conf"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
            - name: cluster
              containerPort: 16379
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: "/etc/redis"
            - name: data
              mountPath: "/var/lib/redis"
      volumes:
        - name: conf
          configMap:
            name: redis
            items:
              - key: "redis-server.sh"
                path: "redis-server.sh"
                mode: 0755
              - key: "redis.conf"
                path: "redis.conf"
        - name: data
          persistentVolumeClaim:
            claimName: redis-2
