---
version: 2
default: &defaults
  working_directory: /home/circleci/project/kube-on-air
  docker:
    - image: archlinux/base:latest
workflows:
  version: 2
  checkout_ansible_host:
    jobs:
      - checkout
      - ansible:
          requires:
            - checkout
      - host:
          requires:
            - checkout
      - cluster:
          requires:
            - checkout
jobs:
  checkout:
    <<: *defaults
    steps:
      - run:
          name: install tar and git/ssh to checkout and create a workspace
          command: pacman -Sy --noconfirm tar git openssh
      - checkout
      - persist_to_workspace:
          root: /home/circleci/project/kube-on-air
          paths:
            - .
  ansible:
    <<: *defaults
    steps:
      - run:
          name: install tar and other tools to build the latest ansible
          command: pacman -Sy --noconfirm tar make git python python-pip
      - attach_workspace:
          at: .
      - run: SUDO= make ci-ansible
  host:
    <<: *defaults
    steps:
      - run:
          name: install tar and other tools to run the test
          command: pacman -Sy --noconfirm tar make git gcc go python python-pip
      - attach_workspace:
          at: .
      - run: SUDO= GOROOT=$HOME/git/go GOPATH=$HOME make ci-test-host
  cluster:
    <<: *defaults
    steps:
      - run:
          name: install tar and other tools to run the test
          command: pacman -Sy --noconfirm tar make git gcc go python python-pip
      - attach_workspace:
          at: .
      - run: SUDO= GOROOT=$HOME/git/go GOPATH=$HOME make ci-test-cluster
