apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: redis-cluster
  name: redis-6
spec:
  resources:
    requests:
      storage: 128Mi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      volume: redis-6
