---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rabbit
subsets:
  - addresses:
      - ip: 10.0.0.13
    ports:
      - port: 5672
