---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  selector:
    app: hello
  type: ClusterIP
  clusterIP: 10.0.0.100
  ports:
    - name: http
      port: 80
      protocol: TCP
