apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-2
  labels:
    app: redis-cluster
    volume: redis-2
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.255.254
    path: "/srv/nfs/redis-2"
    readOnly: false
