apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tikv-cluster
  name: tikv-3
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
