apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2017-10-26T02:18:14Z","generation":1,"labels":{"app":"bandicoot","env":"prod","ver":"2"},"name":"bandicoot-prod","namespace":"default","resourceVersion":"1842","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/bandicoot-prod","uid":"ec3dfde7-b9f3-11e7-b2a4-000016041003"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"bandicoot","env":"prod","ver":"2"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"bandicoot","env":"prod","ver":"2"}},"spec":{"containers":[{"image":"gcr.io/kuar-demo/kuard-amd64:2","imagePullPolicy":"IfNotPresent","name":"bandicoot-prod","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2017-10-26T02:18:16Z","lastUpdateTime":"2017-10-26T02:18:16Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}
  creationTimestamp: 2017-10-26T02:25:11Z
  generation: 2
  labels:
    app: bandicoot
    env: prod
    ver: "2"
  name: bandicoot-prod
  namespace: default
  resourceVersion: "3005"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/bandicoot-prod
  uid: e44c65b5-b9f4-11e7-b2a4-000016041003
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bandicoot
      env: prod
      ver: "2"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bandicoot
        env: prod
        ver: "2"
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:2
        imagePullPolicy: IfNotPresent
        name: bandicoot-prod
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2017-10-26T02:25:12Z
    lastUpdateTime: 2017-10-26T02:25:12Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
