apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yaml"
            - "--storage.tsdb.path=/prometheus/"
          imagePullPolicy: Always
          name: prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prom-config-volume
              mountPath: /etc/prometheus
            - name: prom-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prom-config-volume
          configMap:
            name: prom-config
            defaultMode: 420
       - name: prom-storage-volume
         emptyDir: {}
