kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host:
    http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx
          servicePort: 80
